build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.18"
  amd64: "ghcr.io/home-assistant/amd64-base:3.18"
  armv7: "ghcr.io/home-assistant/armv7-base:3.18"
labels:
  org.opencontainers.image.title: "Dispatcharr"
  org.opencontainers.image.description: "IPTV & stream management with Home Assistant integration"
  org.opencontainers.image.source: "https://github.com/Stainy3244/dispatcharr-hassio-addon"
  org.opencontainers.image.licenses: "MIT"
args:
  DISPATCHARR_VERSION: "latest"
