name: Dispatcharr
version: "0.10.1"
slug: dispatcharr
description: IPTV & stream management with Home Assistant shared storage integration
url: "https://github.com/Stainy3244/dispatcharr"
arch:
  - aarch64
  - amd64
  - armv7
init: false
boot: auto
startup: services
# Persistent storage
map:
  - share:rw
  - media:rw
  - ssl:rw
  - data:rw
ports:
  "9191/tcp": 9191
ports_description:
  "9191/tcp": Web interface
webui: "http://[HOST]:[PORT:9191]"
panel_icon: mdi:play-network
options:
  PGID: 1000
  PUID: 1000
  TZ: ""
  recordings_location: "media"
  custom_recordings_path: ""
  additional_packages: []
  log_level: info
schema:
  PGID: int
  PUID: int
  TZ: str?
  recordings_location: list(share|media|config)?
  custom_recordings_path: str?
  additional_packages:
    - str?
  log_level: list(trace|debug|info|warn|error|fatal)?
# Local build base images
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.18"
  amd64: "ghcr.io/home-assistant/amd64-base:3.18" 
  armv7: "ghcr.io/home-assistant/armv7-base:3.18"


