name: Dispatcharr
version: "0.10.1"
slug: dispatcharr
description: IPTV & stream management with Home Assistant shared storage integration
url: "https://github.com/Stainy3244/dispatcharr"

arch:
  - aarch64
  - amd64
  - armv7

init: false

# Map persistent folders
map:
  - share:rw
  - media:rw
  - ssl:rw
  - data:rw   # added /data for DB and internal files

ports:
  "9191/tcp": 9191

ports_description:
  "9191/tcp": Web interface

webui: "http://[HOST]:[PORT:9191]"
panel_icon: mdi:play-network

startup: services
boot: manual
run-as-root: true   # allow PostgreSQL & user setup to work

options:
  PGID: 1000
  PUID: 1000
  TZ: ""
  recordings_location: "/media/dispatcharr"
  custom_recordings_path: ""
  additional_packages: []
  log_level: info

schema:
  PGID: int
  PUID: int
  TZ: str?
  recordings_location: list(share|media|config)?
  custom_recordings_path: str?
  additional_packages:
    - str?
  log_level: list(trace|debug|info|warn|error|fatal)?

# Use Dispatcharr image (multi-arch)
image: "ghcr.io/stainy3244/dispatcharr-{arch}"


